### ISSUE TITLE
Deploy to Heroku not work

### ISSUE THREAD

**Issue by septk** [lionsharecapital/lionshare-api#35]
Hi,

I try to test deploy to heroku button, and when my node app finish installation, i've error application on heroku. What can I do?

ty

**Comment by septk** [comment]
AssertionError: .id required
      at new Limiter (/Users/davidwebdev/Downloads/lionshare-api-master2/node_modules/ratelimiter/index.js:27:3)
      at ratelimit (/Users/davidwebdev/Downloads/lionshare-api-master2/node_modules/koa-ratelimit/index.js:46:21)
      at dispatch (/Users/davidwebdev/Downloads/lionshare-api-master2/node_modules/koa-compose/index.js:44:32)
      at /Users/davidwebdev/Downloads/lionshare-api-master2/node_modules/koa-compose/index.js:36:12
      at Server.<anonymous> (/Users/davidwebdev/Downloads/lionshare-api-master2/node_modules/koa/lib/application.js:135:7)
      at emitTwo (events.js:106:13)
      at Server.emit (events.js:194:7)
      at parserOnIncoming (_http_server.js:565:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

**Comment by kirillshevch** [comment]
The same issue by trying run it locally, any suggestions? @maksim-s

**Comment by kirillshevch** [comment]
Problem with ratelimit https://github.com/lionsharecapital/lionshare-api/commit/0a0717737bcde76174e7356856f958ffbe2f290a

**Comment by kirillshevch** [comment]
@jorilallo
